### ISSUE TITLE
作者好，我想问下这个语音的播放速度可以调节吗？

### ISSUE THREAD

**Issue by uniquMonte** [fxjs/tzfe-tts#3]
我认为目前的默认播放速度有点点快，不利于学习语言，想调慢一点，是否有相关参数可调节

**Comment by fxjs** [comment]
可通过 `rate` 参数控制：
`
{
  "model": "zh-CN-XiaoxiaoNeural",
  "input": "网关异常，请及时处理。",
  "voice": "rate:0.2|pitch:0"
}
`

**Comment by uniquMonte** [comment]
好的，谢谢
